name       : perl-http-cookies
version    : '6.04'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Cookies-6.04.tar.gz : 0cc7f079079dcad8293fea36875ef58dd1bfd75ce1a6c244cd73ed9523eb13d4
license    : Artistic-Perl-1.0
component  : programming.perl
summary    : HTTP Cookies Module
description: |
    A perl module to for http cookies
builddeps  :
    - perl-http-date
    - perl-http-message
    - perl-uri
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
