name       : perl-http-cookies
version    : '6.10'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Cookies-6.10.tar.gz : e36f36633c5ce6b5e4b876ffcf74787cc5efe0736dd7f487bdd73c14f0bd7007
homepage   : https://metacpan.org/pod/HTTP::Cookies
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : HTTP::Cookies - HTTP cookie jars
description: |
    This class is for objects that represent a "cookie jar" -- that is, a database of all the HTTP cookies that a given LWP::UserAgent object knows about.
builddeps  :
    - perl-clone
    - perl-http-date
    - perl-http-message
    - perl-uri
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
