name       : perl-http-cookies
version    : '6.08'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Cookies-6.08.tar.gz : 49ebb73576eb41063c04bc079477df094496deec805ae033f3be338c23c3af59
homepage   : https://metacpan.org/pod/HTTP::Cookies
license    : Artistic-Perl-1.0
component  : programming.perl
summary    : HTTP Cookies Module
description: |
    A perl module to for http cookies
builddeps  :
    - perl-http-date
    - perl-http-message
    - perl-uri
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
